version: '3.8'

services:

  usuarioMS:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    restart: always

  usuarioPY:
    image: jeanp0/users-microservice:1.0
    build:
      context: .
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - usuarioMS
    environment:
      MONGO_HOST: usuarioMS

  usuarioUI:
    image: jeanp0/users-frontend:1.0
    build:
      context: ../users-frontend/ # relative path of the front project
    ports:
      - 80:80
    restart: always

volumes:
  mongo-data: